const DASHBOARD_HOME = "/home";
const COLORS = "/colors";
const DASHBOARD_LOGIN = "/auth/login";
const DASHBOARD_REGISTER = "/auth/register";
const DASHBOARD_FORGOT = "/auth/forgot-password";
const DASHBOARD_FORGOT_FORM = "/auth/forgot-passwordForm";
const DASHBOARD_EMAIL_CONFIRM = "/auth/email-confirm";
const DASHBOARD_EMAIL_CHANGE = "/auth/email-change";
const DASHBOARD_PROFILE = "/profile/update-profile";

const PRIVATE_ROUTES = [DASHBOARD_HOME];
const PROFILE_ROUTES = [DASHBOARD_PROFILE];
const AUTH_ROUTES = [
  DASHBOARD_LOGIN,
  DASHBOARD_REGISTER,
  DASHBOARD_FORGOT,
  DASHBOARD_FORGOT_FORM,
  DASHBOARD_EMAIL_CONFIRM,
  DASHBOARD_EMAIL_CHANGE,
];

export {
  DASHBOARD_HOME,
  AUTH_ROUTES,
  PRIVATE_ROUTES,
  PROFILE_ROUTES,
  COLORS,
  DASHBOARD_LOGIN,
  DASHBOARD_REGISTER,
  DASHBOARD_FORGOT,
  DASHBOARD_FORGOT_FORM,
  DASHBOARD_EMAIL_CONFIRM,
  DASHBOARD_EMAIL_CHANGE,
  DASHBOARD_PROFILE,
};

